name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: sbt test
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: + test
  deploy:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - needs: test
      - name: sbt deploy
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: + publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}