name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: sbt test
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: + test
      - name: sbt package
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: + package
      - name: set up python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark
      - name: run python tests
        run: |
          cd python
          sh run-tests.sh
  deploy:
    if: contains(github.ref, 'master')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: sbt deploy
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: + publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}